[project]
name = "ai-nids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black[jupyter]>=25.0.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "pytest>=9.0.3",
    "pyyaml>=6.0.3",
    "ruff>=0.15.1",
    "scikit-learn>=1.8.0",
    "taskipy>=1.14.1",
    "typer>=0.25.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.black]
target-version = ["py312"]

[tool.taskipy.tasks]
format    = "uv run black . && uv run ruff check --fix ."
lint      = "uv run black --check . && uv run ruff check ."
precommit = "uv run pre-commit run --all-files"
test      = "uv run pytest"
dataset   = "uv run bin/download_dataset.py"
train     = "uv run bin/train.py"
evaluate  = "uv run bin/evaluate.py"
detect    = "uv run bin/detect.py"

[dependency-groups]
dev = [
    "pre-commit>=4.6.0",
]
